spring.application.name=parkIQ

spring.datasource.url=jdbc:postgresql://localhost:5432/Parking
spring.datasource.username=postgres
spring.datasource.password=Dhivya@2810

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring-boot-starter-security
spring-boot-starter-oauth2-client

